# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-12 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180712_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 12, 48, 18, 463578, tzinfo=utc)),
        ),
    ]
