# Generated by Django 2.0.7 on 2018-07-16 20:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180712_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
