# Generated by Django 2.1 on 2018-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180809_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteraddresse',
            name='token',
            field=models.CharField(max_length=60),
        ),
    ]
